### PR TITLE
Added myself to manifesto

### PR DESCRIPTION
**Pull request by dbrgn**
I run a private XMPP server (=no public registration, but connected to XMPP network).

I think "regular" server operators should also have a way to show their commitment to a more secure network. Ubiquitous S2S encryption won't work if not all servers support it. Therefore it is important that not only the public service providers adhere to these guidelines/goals, but also people that just run XMPP servers for themselves & friends.

If you want to differentiate between public service providers and "private or unimportant service providers", why not create two different sections for the signatures? :)

Thanks for creating this manifesto, it's an important step towards more secure communication online!

### CODE REVIEW

**Comment by stpeter** [comment]
I'll add your signature manually (not via pull request).

We need clearer terminology for servers. To me, "private" means "not connected to the network" (e.g., behind a company firewall), "public" means "connected to the network" (i.e., federated), "open" means "accepting registration from anyone", and "closed" means "registration is restricted". Your suggestions are welcome. :-)

**Comment by dbrgn** [comment]
Ah, alright. In that case I run a public closed server :)

**Comment by stpeter** [comment]
Yeah that sounds strange, doesn't it? :-) "Private, federated server" sounds more correct.

**Comment by dbrgn** [comment]
Yeah, doesn't sound bad.

**Comment by stpeter** [comment]
Another recent signer used that term, and it sounded right. But on the other hand we also talk about the "public network", and can you connect a private server to the public network? Maybe we're just confused... ;-)

**Pull request closed without merging**
