### PR TITLE
Update manifesto.txt

### PR DESCRIPTION
**Pull request by SvenBunge**
Signed the Manifesto. I'm really glad that you've created the manifesto.

### CODE REVIEW

**Comment by SvenBunge** [comment]
I'm running two XMPP-Servers. I've investigated why Openfire does not encrypt S2S to ejabberd and other servers and I've contributed the following patch to openfire: 
http://community.igniterealtime.org/message/236060
http://issues.igniterealtime.org/browse/OF-745

I hope that they will release a new version with the patch soon.

**Comment by imaginator** [comment]
That's great.

Hoping that we get this sorted soon.

On 10 March 2014 23:09, svenbunge notifications@github.com wrote:

> I'm running two XMPP-Servers. I've investigated why Openfire does not
> encrypt S2S to ejabberd and other servers and I've contributed the
> following patch to openfire:
> http://community.igniterealtime.org/message/236060
> http://issues.igniterealtime.org/browse/OF-745
> 
> I hope that they will release a new version with the patch soon.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/stpeter/manifesto/pull/60#issuecomment-37241004
> .

## 

Simon Tennant | buddycloud.com | +49 17 8545 0880 | office hours:
goo.gl/tQgxP

**Comment by stpeter** [comment]
Hi Sven, would you mind if we list the two servers that you operate? 

Let us know if we can help connect you with the Openfire developers or encourage them to take action.

**Comment by SvenBunge** [comment]
Why not, but both servers are only for selected persons: nnga.info is a jabber-server of an association and holisticon.de is a server of a consulting company with the same name. - Only for employees.

Regarding Openfire: There are some other issues with S2S and I'm still in touch with the developers in the discussion board on the website. The mentioned patch above is by far the most important patch and I think that they not have merged it into openfire because the S2S-developer and the openfire project lead is not active in the moment ... If you have some hints: My ear is open :-D
I've provided a drop-in-patch for all other openfire operators but it's only available in the discussion board.

**Pull request closed without merging**
