### PR TITLE
Add Vasil Kolev to the signatories

### PR DESCRIPTION
**Pull request by krokodilerian**

### CODE REVIEW

**Comment by stpeter** [comment]
Added manually. What XMPP service(s) do you operate?

**Comment by krokodilerian** [comment]
ludost.net

В 08:04 -0800 на 18.02.2014 (вт), Peter Saint-Andre написа:

> Added manually. What XMPP service(s) do you operate?
> 
> —
> Reply to this email directly or view it on GitHub.

## 

Regards,
Vasil Kolev

**Comment by stpeter** [comment]
Thanks. Do you mind if we add that to your signature in the manifesto?

**Comment by krokodilerian** [comment]
No, no problem.

В 10:43 -0800 на 18.02.2014 (вт), Peter Saint-Andre написа:

> Thanks. Do you mind if we add that to your signature in the manifesto?
> 
> —
> Reply to this email directly or view it on GitHub.

## 

Regards,
Vasil Kolev

**Comment by stpeter** [comment]
Done! Thanks again.

**Pull request closed without merging**
